### PR TITLE
Languages: add support for mermaid graphing

### PR DESCRIPTION
**Pull request by simonweil**
I really like to make graphs using [Mermaid](http://knsv.github.io/mermaid)
so I hope you will accept the pull request.

Try this out (with ````mermaid` as the language):

``` mermaid
 graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

An example of a sequence diagram:

``` mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice->John: Hello John, how are you?
    loop Healthcheck
        John->John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail...
    John-->Alice: Great!
    John->Bob: How about you?
    Bob-->John: Jolly good!
```

Example code for a gantt diagram

`````` mermaid
gantt
        dateFormat  YYYY-MM-DD
        title Adding GANTT diagram functionality to mermaid
        section A section
        Completed task            :done,    des1, 2014-01-06,2014-01-08
        Active task               :active,  des2, 2014-01-09, 3d
        Future task               :         des3, after des2, 5d
        Future task2               :         des4, after des3, 5d
        section Critical tasks
        Completed task in the critical line :crit, done, 2014-01-06,24h
        Implement parser and jison          :crit, done, after des1, 2d
        Create tests for parser             :crit, active, 3d
        Future task in critical line        :crit, 5d
        Create tests for renderer           :2d
        Add to mermaid                      :1d```
``````

### CODE REVIEW

**Comment by rhysd** [comment]
Thank you for nice PR:smile:
I want to merge this.

Could you include only necessary files in `node_modules`?  I want to reduce the size of package as small as possible.  It seems that JavaScript, css, and license files are needed.

**Comment by simonweil** [comment]
Thanks, done.
I left only the files that seemed to me important, is it OK now?

**Comment by rhysd** [comment]
OK, thanks :blush:

**Comment by simonweil** [comment]
Thank you!

**Pull request merged**
